package errorsx

import (
	"errors"
	"fmt"
)

// GoxError signals the caller the error was generated by Gox runtime.
var GoxError = errors.New("gox")

func JoinErrors(goxErr error, message string, sourceErr error) error {
	return fmt.Errorf("%w: %w: %s: %w", GoxError, goxErr, message, sourceErr)
}
