// Code generated by meh DO NOT EDIT.
package apihttp

import (
	"find-doctor/service/operations/send_user_message"
	"net/http"

	"github.com/victormf2/gosyringe"
	"github.com/victormf2/gox/httpx"
)

func AddRoutes(c *gosyringe.Container, mux *http.ServeMux) {

	gosyringe.RegisterScoped[*send_user_message.Operation](c, send_user_message.NewOperation)

	mux.HandleFunc("POST /messages", func(w http.ResponseWriter, r *http.Request) {
		c := gosyringe.CreateChildContainer(c)

		var input send_user_message.Input
		err := httpx.BindJSON(r, &input)
		if err != nil {
			ErrorHandler(w, r, err, c)
			return
		}

		operation, err := gosyringe.Resolve[*send_user_message.Operation](c)
		if err != nil {
			ErrorHandler(w, r, err, c)
			return
		}

		output, err := operation.Do(&input)
		if err != nil {
			ErrorHandler(w, r, err, c)
			return
		}

		err = httpx.WriteJSON(w, &output)
		if err != nil {
			ErrorHandler(w, r, err, c)
			return
		}
	})
}
